[package]
name    = "lrinser_laser_etcher"
version = "0.2.0"
authors = ["Totobird Creations"]
edition = "2021"

[dependencies]
image = "0.23.14"
scraper = "0.13.0"
reqwest = { version = "0.11.11", features = ["blocking"] }
serde_json = "1.0.48"
