[package]
name    = "lrinser_laser_etcher"
version = "0.2.0"
authors = ["Totobird Creations"]
edition = "2021"

[dependencies]
image       = "0.23.14"
loggerithm  = "1"
static_init = "1"
colored     = "2"
chrono      = "0.4.22"
